Algoritmo "9 questão"
// Autor(a)    : Gabriel S A Matos
// Data atual  : 27/09/2022
Var
reaal, dol: real

Inicio
Escreval ("Escreva quanto dinherio você tem: ")
leia (reaal)
dol <- 5.38
reaal <- reaal / dol
//valor do dólar hoje é 5,38 reais
Escreval ("Você consegue comprar", reaal, " dólares.")

Escreval ("Escreva quantos dólares você tem: ")
leia (dol)
reaal <- 5.38
dol <- reaal * dol
//valor do dólar hoje é 5,38 reais
Escreval ("Você consegue comprar", dol, " reais.")

Fimalgoritmo